### ISSUE TITLE
How to display pseudo and asm code at the same time.

### ISSUE THREAD

**Issue by lieanu** [joelpx/plasma#57]
Like this pic.
![](https://raw.githubusercontent.com/joelpx/plasma/master/images/visual.png)

**Comment by joelpx** [comment]
Only some instructions are displayed like in C (for example : add, mov, ...).
For this pic, you can run : 

    $ ./run_plasma.py -i tests/server.bin
    >> v 0x4009c6

If you are in a function, and you want to print the pseudo decompilation, press `tab` on an instruction.

If the analyzer didn't pass through this function (it doesn't on this one), you can press `c` to create code. Note: there is no auto-reload for the moment, if the analyzer has modified the content, you should quit the visual mode and come back. If you want to see the state of the analyzer, you can run the command `analyzer`.

If you want to print original instructions you can press `I`. After one press : 
1. no pseudo instructions, it prints the instrucion mnemonic. Also all pointers dereferenced in 3) were not here.
2. mnemonic + original operand string given by capstone.
3. Then it comes to the beginning, it prints instructions + pseudo instructions.

Did my answer help you ?

**Comment by joelpx** [comment]
Note: the screenshot is old, I've removed comments with the # on the right. The best will be to used the `I` key.

**Comment by lieanu** [comment]
Hey, 

Thanks for your reply. 
The old screenshot which display pseudo decompilation with asm comments is good for learning asm instrs. while `I` command is not so straightforward(swtich needs time :smile: ).

**Comment by joelpx** [comment]
I don't known if I will add it again, but I take note. For the moment, you can use this patch : 

    diff --git a/plasma/lib/output.py b/plasma/lib/output.py
    index 28e4499..a438e88 100644
    --- a/plasma/lib/output.py
    +++ b/plasma/lib/output.py
    @@ -666,6 +666,7 @@ class OutputAbs():
     
                 self._post_asm_inst(i, tab)
     
    +        self._comment(" # " + self.get_inst_str(i))
             self._inline_comment(i)
             self._new_line()

**Comment by lieanu** [comment]
Thanks! 👍
