### ISSUE TITLE
v command not working, 256 colors problem

### ISSUE THREAD

**Issue by ibrahimkaraguzel** [joelpx/plasma#58]
Hello;
i have compiled plasma with all dependencies. I run plasma with your test binaries. And the "x" command works. Like i enter "x main" and enter, i see a good-looking disassembly.

Bu the the v command doesn't work, it gives a traceback error :
`# plasma -i /var/pisi/plasma-0.0-1/work/plasma-0.0/tests/server.bin 
plasma> v main 

Traceback (most recent call last):
                                    File "/usr/lib/python3.4/site-packages/plasma/lib/ui/console.py", line 526, in exec_command
                                                                                                                                   c.callback_exec(args)
                                                                                                                                                          File "/usr/lib/python3.4/site-packages/plasma/lib/ui/console.py", line 655, in __exec_v
                                                                Visual(self.gctx, ctx, self.analyzer, self.api)
                                                                                                                 File "/usr/lib/python3.4/site-packages/plasma/lib/ui/visual.py", line 102, in __init__
                      curses.init_pair(1, 253, 66) # for the highlight search
                                                                             _curses.error: init_pair() returned ERR
                                                                                                                    plasma>`

**Comment by joelpx** [comment]
It looks like your terminal doesn't support 256 colors. What is your terminal ?
Run this command to see if it returns "256" : `tput colors`.
Thanks.

**Comment by ibrahimkaraguzel** [comment]
the command returns 8
what shall i do to turn it to 256

**Comment by joelpx** [comment]
What terminal are you using ?

**Comment by ibrahimkaraguzel** [comment]
Os X terminal with solarized theme (it is colorful though?)

**Comment by joelpx** [comment]
Try to add this line in your bashrc (or equivalent) : `export TERM=xterm-256color`

Or try this (I'm not a mac user) : http://deploymentzone.com/2012/03/08/solarized-vim-256-colors-terminal-app-and-osx-lion/

**Comment by ibrahimkaraguzel** [comment]
ok i got the situation!
default os x termial is already 256! No problem
But under my machine i am working with a docker machine which uses a linux distribution. And that linux terminal is 8 colored.
Thanks anyway :)
