### ISSUE TITLE
Dockerfile doesn't work fine

### ISSUE THREAD

**Issue by BokenCLS** [joelpx/plasma#65]
Hi,

I'm trying to execute it with Dockerfile but the files inside don't match with the file that there are on folder. By example:
RUN /plasma/requirements.sh
and requirements.sh doesn't exist on anywhere.

Regards.

**Comment by joelpx** [comment]
Thank you. I forgot to update the dockerfile.
I'm not an expert of docker, can you tell me if it's good ?

**Comment by BokenCLS** [comment]
Now this is the new error:
-------------------------------------------------------------------------------------------
install -m0644 ./capstone.pc /usr/lib/pkgconfig/
/
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Storing debug log for failure in /root/.pip/pip.log
python3: can't open file 'setup.py': [Errno 2] No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory
The command '/bin/sh -c /plasma/install.sh' returned a non-zero code: 2
-------------------------------------------------------------------------------------------

Please try Docker image on local and push after.

Thank you very much.
Regards.
